version: '3.1'
services:
  db:
    image: mariadb:latest
    container_name: pizza_db
    restart: always
    environment:
      MARIADB_USER: user
      MARIADB_DATABASE: pizza
      MARIADB_PASSWORD: dev-secret-pw
      MARIADB_ROOT_PASSWORD: root-secret-pw
    ports:
      - 3306:3306